const recordArray = [
    {name: 'pepe', date: '5/8/90', description: 'tukiscbdsjcbdhjscbhjsdbchjsbchjsbchjsbcjbhs', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
    {name: 'pepe', date: '5/8/90', description: 'tukis', category: 'shoes'},
]

export default recordArray;